--- #YAML:1.0
name: Games-YASudoku
version: 0.01
author:
  - Andrew Wyllie <wyllie@dilex.net>
abstract: Yet Another Sudoku Solver
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
